-- Deploy 10 Premium Auction Items to Production
-- Run on production database: mysql -u [user] -p silentbidbuddy < 002-add-premium-items.sql

INSERT INTO items (item_number, title, description, fair_market_value, starting_bid, auction_end_time, image_url) VALUES
(101, 'Handcrafted Walnut Executive Desk', 'A stunning solid walnut executive desk with hand-carved details, featuring three spacious drawers, a leather top, and brass hardware. Measures 60"L x 30"W x 30"H. Perfect for the discerning professional looking to elevate their workspace. Includes matching leather chair.', 2500.00, 400.00, DATE_ADD(NOW(), INTERVAL 14 DAY), '/images/items/item-101.jpg'),
(102, 'Vintage Omega Seamaster Watch', 'Classic 1970s Omega Seamaster automatic wristwatch with original steel case, professional dial, date window, and 300m water resistance. Recently serviced with new crystal. Comes with original box and papers. A timeless piece that works as hard as you do.', 3500.00, 500.00, DATE_ADD(NOW(), INTERVAL 14 DAY), '/images/items/item-102.jpg'),
(103, 'First Edition Harry Potter Box Set', 'Complete set of all 7 Harry Potter books in first editions with dust jackets in excellent condition. Signed by J.K. Rowling on the Philosopher\'s Stone. Includes Chamber of Secrets, Prisoner of Azkaban, Goblet of Fire, Order of Phoenix, Half-Blood Prince, and Deathly Hallows. A collector\'s dream.', 4000.00, 600.00, DATE_ADD(NOW(), INTERVAL 14 DAY), '/images/items/item-103.jpg'),
(104, 'Professional Espresso Machine - La Marzocco', 'Commercial-grade La Marzocco Linea Mini espresso machine with dual boiler system, PID temperature control, and rotary pump. Pristine condition, barely used. Capable of producing café-quality espresso, cappuccino, and latte at home. Perfect for the serious coffee enthusiast.', 2800.00, 450.00, DATE_ADD(NOW(), INTERVAL 14 DAY), '/images/items/item-104.jpg'),
(105, 'Abstract Expressionist Oil Painting', 'Original 48"x36" oil on canvas by emerging artist featured in LACMA shows. Vibrant composition with bold brushstrokes in blues, golds, and crimsons. Signed and dated 2022. Comes with certificate of authenticity and exhibition history. A stunning focal point for any modern interior.', 3200.00, 500.00, DATE_ADD(NOW(), INTERVAL 14 DAY), '/images/items/item-105.jpg'),
(106, 'Rare 1961 Fender Stratocaster Guitar', 'Iconic sunburst finish Fender Stratocaster with original three-ply pickguard, serial number places it in coveted "CBS era." Plays beautifully with warm tone, all original hardware, case included. A guitar that defined generations of rock and roll music.', 4500.00, 700.00, DATE_ADD(NOW(), INTERVAL 14 DAY), '/images/items/item-106.jpg'),
(107, 'Japanese Bonsai Master Collection', '10-piece premium bonsai tree collection including 80-year-old Japanese maple, 60-year-old juniper, flowering plum, and seven other rare species. Each includes handcrafted ceramic pot, nutrient package, and care guide by master cultivator. Investment pieces that appreciate over time.', 5000.00, 750.00, DATE_ADD(NOW(), INTERVAL 14 DAY), '/images/items/item-107.jpg'),
(108, 'Leica M6 Film Camera with Lenses', 'Legendary rangefinder camera in chrome finish with pristine glass. Includes 35mm f/2.8 Summaron, 50mm f/2 Summicron, and 90mm f/4 Elmar lenses. All optics are clean with no fungus. Complete with original Leica case and lens caps. The gold standard for street and documentary photography.', 3800.00, 600.00, DATE_ADD(NOW(), INTERVAL 14 DAY), '/images/items/item-108.jpg'),
(109, 'Rolex Submariner Steel Watch - 2019', 'Rolex Submariner 41mm stainless steel with black dial, date window, and ceramic bezel. Reference 124060 purchased in 2019, full set with box, papers, and warranty. Excellent condition with light signs of wear. Keeps perfect time and fully operational. An investment that holds value.', 6500.00, 1000.00, DATE_ADD(NOW(), INTERVAL 14 DAY), '/images/items/item-109.jpg'),
(110, 'Modern Art Glass Sculpture Collection', 'Set of 3 handblown glass sculptures by renowned artist Dale Chihuly. Large blue and amber piece (24" tall), medium clear with ruby accent (16" tall), and small green vessel (8" tall). Each is unique, signed, and numbered. Museum quality with provenance documentation included.', 5500.00, 800.00, DATE_ADD(NOW(), INTERVAL 14 DAY), '/images/items/item-110.jpg');
